# Site settings
title: Alice Rose
email: hello@alicero.se
description: > # this means to ignore newlines until "baseurl:"
  I am an experienced software developer and frontend specialist.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alicero.se" # the base hostname & protocol for your site
twitter_username: heldinz
github_username:  heldinz
linkedin_username: heldinz

# Build settings
markdown: kramdown
